-- FITNADO Phase 03: Product Research Database Migration
-- Table: table_product_research

CREATE TABLE IF NOT EXISTS `table_product_research` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `normalized_name` varchar(255) DEFAULT NULL,
  `category_hint` varchar(255) DEFAULT NULL,
  `brand_hint` varchar(255) DEFAULT NULL,
  `platform` varchar(50) NOT NULL DEFAULT 'manual',
  `source_url` text NOT NULL,
  `normalized_url` varchar(500) DEFAULT NULL,
  `external_product_id` varchar(100) DEFAULT NULL,
  `image_url` text DEFAULT NULL,
  `price` double DEFAULT NULL,
  `original_price` double DEFAULT NULL,
  `currency` varchar(10) DEFAULT 'VND',
  `sales_count` int(11) DEFAULT NULL,
  `rating` double DEFAULT NULL,
  `review_count` int(11) DEFAULT NULL,
  `commission_rate` double DEFAULT NULL,
  `commission_value` double DEFAULT NULL,
  `estimated_gmv` double DEFAULT NULL,
  `creator_count` int(11) DEFAULT NULL,
  `video_count` int(11) DEFAULT NULL,
  `top_video_views` bigint(20) DEFAULT NULL,
  `problem_solved` text DEFAULT NULL,
  `target_audience` text DEFAULT NULL,
  `research_notes` text DEFAULT NULL,
  `primary_keyword` varchar(255) DEFAULT NULL,
  `demand_score` double DEFAULT NULL,
  `content_score` double DEFAULT NULL,
  `commission_score` double DEFAULT NULL,
  `competition_score` double DEFAULT NULL,
  `seo_score` double DEFAULT NULL,
  `total_score` double DEFAULT NULL,
  `score_breakdown` text DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'DISCOVERED',
  `reject_reason` varchar(255) DEFAULT NULL,
  `id_product` int(11) unsigned DEFAULT NULL,
  `raw_data` longtext DEFAULT NULL,
  `history` longtext DEFAULT NULL,
  `date_created` int(11) NOT NULL DEFAULT 0,
  `date_updated` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_platform` (`platform`),
  KEY `idx_id_product` (`id_product`),
  KEY `idx_total_score` (`total_score`),
  KEY `idx_external_id` (`external_product_id`),
  KEY `idx_normalized_url` (`normalized_url`(191)),
  KEY `idx_normalized_name` (`normalized_name`(191)),
  KEY `idx_date_created` (`date_created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
