-- FITNADO Phase 05 Database Migration: AI Content Engine
-- Non-destructive DDL

CREATE TABLE IF NOT EXISTS `table_ai_content` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_product` int(11) unsigned NOT NULL,
  `id_research` int(11) unsigned DEFAULT NULL,
  `content_type` varchar(50) NOT NULL COMMENT 'product_analysis, tiktok_hooks, tiktok_script, seo_content, review_draft, buying_guide, faq',
  `title` varchar(255) NOT NULL DEFAULT '',
  `language` varchar(10) NOT NULL DEFAULT 'vi',
  `tone` varchar(50) NOT NULL DEFAULT 'FITNADO_DEFAULT',
  `target_duration` int(11) DEFAULT NULL COMMENT 'For TikTok script: 15, 30, 45, 60 seconds',
  `content_angle` varchar(100) DEFAULT NULL,
  `content_text` longtext DEFAULT NULL COMMENT 'Formatted readable content / markdown',
  `structured_data` longtext DEFAULT NULL COMMENT 'JSON structured representation',
  `version` int(11) NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'REVIEW_REQUIRED' COMMENT 'GENERATING, GENERATED, REVIEW_REQUIRED, APPROVED, REJECTED, OUTDATED, APPLIED',
  `reject_reason` varchar(255) DEFAULT NULL,
  `source_hash` varchar(64) NOT NULL DEFAULT '',
  `is_outdated` tinyint(1) NOT NULL DEFAULT 0,
  `provider` varchar(50) NOT NULL DEFAULT 'mock',
  `model` varchar(100) NOT NULL DEFAULT 'gemini-1.5-flash',
  `prompt_version` varchar(50) NOT NULL DEFAULT 'v1',
  `token_usage` varchar(255) DEFAULT NULL COMMENT 'JSON token usage and duration',
  `quality_check` longtext DEFAULT NULL COMMENT 'JSON quality check result',
  `applied_at` int(11) DEFAULT NULL,
  `applied_by` varchar(100) DEFAULT NULL,
  `applied_target` varchar(100) DEFAULT NULL,
  `date_created` int(11) NOT NULL DEFAULT 0,
  `date_updated` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_product_type_version` (`id_product`, `content_type`, `version`),
  KEY `idx_product_active` (`id_product`, `is_active`),
  KEY `idx_status` (`status`),
  KEY `idx_content_type` (`content_type`),
  KEY `idx_source_hash` (`source_hash`),
  KEY `idx_date_created` (`date_created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `table_ai_content_job` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_product` int(11) unsigned NOT NULL,
  `batch_id` varchar(64) DEFAULT NULL,
  `content_types` varchar(255) NOT NULL DEFAULT 'product_analysis,tiktok_hooks,tiktok_script,seo_content,review_draft,faq',
  `language` varchar(10) NOT NULL DEFAULT 'vi',
  `tone` varchar(50) NOT NULL DEFAULT 'FITNADO_DEFAULT',
  `target_duration` int(11) NOT NULL DEFAULT 30,
  `content_angle` varchar(100) NOT NULL DEFAULT 'Problem/Solution',
  `priority` int(11) NOT NULL DEFAULT 10,
  `status` varchar(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, RUNNING, SUCCESS, FAILED, CANCELLED',
  `attempts` int(11) NOT NULL DEFAULT 0,
  `max_attempts` int(11) NOT NULL DEFAULT 3,
  `error_message` text DEFAULT NULL,
  `results_summary` text DEFAULT NULL,
  `started_at` int(11) DEFAULT NULL,
  `completed_at` int(11) DEFAULT NULL,
  `duration` double DEFAULT NULL,
  `date_created` int(11) NOT NULL DEFAULT 0,
  `date_updated` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_product_job` (`id_product`),
  KEY `idx_job_status` (`status`),
  KEY `idx_batch_id` (`batch_id`),
  KEY `idx_date_created` (`date_created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `table_product_content_backup` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `id_product` int(11) unsigned NOT NULL,
  `id_content` int(11) unsigned NOT NULL,
  `field_name` varchar(100) NOT NULL,
  `old_value` longtext DEFAULT NULL,
  `new_value` longtext DEFAULT NULL,
  `backup_reason` varchar(255) NOT NULL DEFAULT 'APPLY_AI_CONTENT',
  `created_by` varchar(100) NOT NULL DEFAULT 'admin',
  `date_created` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_product_backup` (`id_product`),
  KEY `idx_content_backup` (`id_content`),
  KEY `idx_date_created` (`date_created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
