-- FITNADO Phase 06 Database Migration: AI Video Production Engine
-- Non-destructive DDL

CREATE TABLE IF NOT EXISTS `table_ai_video` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_product` int(11) unsigned NOT NULL,
  `id_content` int(11) unsigned NOT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `video_type` varchar(50) NOT NULL DEFAULT 'TIKTOK_9_16' COMMENT 'TIKTOK_9_16, YOUTUBE_SHORTS, PRODUCT_SHOWCASE',
  `aspect_ratio` varchar(20) NOT NULL DEFAULT '9:16' COMMENT '9:16, 1:1, 16:9',
  `target_duration` int(11) NOT NULL DEFAULT 30 COMMENT '15, 30, 45, 60 seconds',
  `voice_id` varchar(100) NOT NULL DEFAULT 'vi-VN-Standard-A',
  `template_id` varchar(100) NOT NULL DEFAULT 'PROBLEM_SOLUTION',
  `scenes_data` longtext DEFAULT NULL COMMENT 'JSON structured scenes with assets and shot plan',
  `script_hash` varchar(64) NOT NULL DEFAULT '',
  `version` int(11) NOT NULL DEFAULT 1,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `is_outdated` tinyint(1) NOT NULL DEFAULT 0,
  `provider` varchar(50) NOT NULL DEFAULT 'mock' COMMENT 'mock, creatify, arcads, heygen, manual',
  `provider_job_id` varchar(100) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'READY' COMMENT 'DRAFT, WAITING_ASSET, READY, QUEUED, PROCESSING, RENDERED, VALIDATING, REVIEW_REQUIRED, APPROVED, REJECTED, FAILED, ARCHIVED',
  `reject_reason` varchar(255) DEFAULT NULL,
  `video_file` varchar(255) DEFAULT NULL COMMENT 'Local relative path: upload/video/...mp4',
  `thumbnail` varchar(255) DEFAULT NULL COMMENT 'Local relative path: upload/video/...jpg',
  `duration_actual` double DEFAULT NULL COMMENT 'Actual duration in seconds',
  `width` int(11) DEFAULT NULL COMMENT 'Video width in pixels',
  `height` int(11) DEFAULT NULL COMMENT 'Video height in pixels',
  `file_size` bigint(20) unsigned DEFAULT NULL COMMENT 'File size in bytes',
  `cost_estimate` double DEFAULT NULL COMMENT 'Cost in USD or provider credits',
  `quality_report` longtext DEFAULT NULL COMMENT 'JSON media validation and QC results',
  `reviewed_by` varchar(100) DEFAULT NULL,
  `reviewed_at` int(11) DEFAULT NULL,
  `date_created` int(11) NOT NULL DEFAULT 0,
  `date_updated` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_product_video` (`id_product`, `is_active`),
  KEY `idx_content_video` (`id_content`),
  KEY `idx_status` (`status`),
  KEY `idx_provider` (`provider`),
  KEY `idx_script_hash` (`script_hash`),
  KEY `idx_date_created` (`date_created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `table_ai_video_job` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_video` int(11) unsigned NOT NULL,
  `provider` varchar(50) NOT NULL DEFAULT 'mock',
  `provider_job_id` varchar(100) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, RUNNING, SUCCESS, FAILED, CANCELLED',
  `attempts` int(11) NOT NULL DEFAULT 0,
  `max_attempts` int(11) NOT NULL DEFAULT 3,
  `next_poll_at` int(11) DEFAULT NULL,
  `poll_count` int(11) NOT NULL DEFAULT 0,
  `error_message` text DEFAULT NULL,
  `results_summary` text DEFAULT NULL,
  `started_at` int(11) DEFAULT NULL,
  `completed_at` int(11) DEFAULT NULL,
  `duration` double DEFAULT NULL,
  `date_created` int(11) NOT NULL DEFAULT 0,
  `date_updated` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_video_id` (`id_video`),
  KEY `idx_status` (`status`),
  KEY `idx_next_poll` (`next_poll_at`),
  KEY `idx_date_created` (`date_created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `table_ai_video_asset` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_video` int(11) unsigned NOT NULL,
  `scene_number` int(11) NOT NULL DEFAULT 1,
  `asset_type` varchar(50) NOT NULL DEFAULT 'PRODUCT_PHOTO' COMMENT 'PRODUCT_PHOTO, PRODUCT_VIDEO, BROLL, LOGO, CTA_OVERLAY, VOICE_AUDIO, CAPTIONS',
  `source_type` varchar(50) NOT NULL DEFAULT 'PRODUCT_DB' COMMENT 'PRODUCT_DB, GALLERY_DB, MANUAL_UPLOAD, AI_GENERATED, EXTERNAL_REF',
  `source_ref` text NOT NULL COMMENT 'Local path or reference URL',
  `file_size` bigint(20) unsigned DEFAULT NULL,
  `is_approved` tinyint(1) NOT NULL DEFAULT 1,
  `notes` varchar(255) DEFAULT NULL,
  `date_created` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_video_scene` (`id_video`, `scene_number`),
  KEY `idx_asset_type` (`asset_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
